version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - nakedret
    - bodyclose
    - errorlint
  disable:
    # Disabled linters - too noisy for CLI tools or not applicable
    - gosec      # Many false positives for CLI (file ops, exec, etc.)
    - revive     # Too verbose style checks
    - gocritic   # Style checks (ifElseChain, singleCaseSwitch) are too opinionated
    - unparam    # Noisy for interfaces and callbacks
    - prealloc   # Micro-optimisation, not critical
    - noctx      # net.Listen doesn't need context for quick port checks

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-tags:
      - style           # Style checks are too opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      # Disabled rules:
      # - exported (too verbose for internal packages)
      # - package-comments (not needed for internal packages)
      # - unused-parameter (noisy for interfaces/callbacks)
  gosec:
    excludes:
      - G101  # Potential hardcoded credentials - false positives on variable names
      - G104  # Audit errors not checked
      - G204  # Subprocess launched with variable - intentional for CLI tool
      - G301  # Directory permissions 0755 - appropriate for user config
      - G304  # File inclusion via variable - intentional for CLI tool
      - G306  # WriteFile permissions 0644 - appropriate for config files

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes:
      - github.com/kanzi/kindplane

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: _test\.go
      text: "SA1019:"  # Allow deprecated APIs in tests (e.g., fake.NewSimpleClientset)
    - linters:
        - govet
      text: 'shadow: declaration of "err"'
  max-issues-per-linter: 0
  max-same-issues: 0
