version: '3'

vars:
  BINARY_NAME: kindplane
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: >-
    -s -w
    -X main.Version={{.VERSION}}
    -X main.Commit={{.COMMIT}}
    -X main.BuildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} ./cmd/kindplane

  build:all:
    desc: Build for all platforms
    deps: [clean]
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-amd64 ./cmd/kindplane
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-arm64 ./cmd/kindplane
      - GOOS=linux GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-amd64 ./cmd/kindplane
      - GOOS=linux GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-arm64 ./cmd/kindplane
      - GOOS=windows GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/kindplane

  install:
    desc: Install locally to $GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" ./cmd/kindplane

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:short:
    desc: Run short tests only
    cmds:
      - go test -v -short ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run linter and fix issues
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - command -v goimports >/dev/null && goimports -w . || echo "goimports not installed, skipping"

  tidy:
    desc: Tidy and verify dependencies
    cmds:
      - go mod tidy
      - go mod verify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  dev:
    desc: Build and show help
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} --help

  dev:init:
    desc: Build and run init command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} init --force

  dev:up:
    desc: Build and run up command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} up

  dev:down:
    desc: Build and run down command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} down

  dev:status:
    desc: Build and run status command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} status

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  release:snapshot:
    desc: Create a snapshot release (requires goreleaser)
    cmds:
      - goreleaser release --snapshot --clean

  tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/goreleaser/goreleaser@latest
