version: '3'

vars:
  BINARY_NAME: kindplane
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: >-
    -s -w
    -X main.Version={{.VERSION}}
    -X main.Commit={{.COMMIT}}
    -X main.BuildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} ./cmd/kindplane

  build:all:
    desc: Build for all platforms
    deps: [clean]
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-amd64 ./cmd/kindplane
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-arm64 ./cmd/kindplane
      - GOOS=linux GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-amd64 ./cmd/kindplane
      - GOOS=linux GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-arm64 ./cmd/kindplane
      - GOOS=windows GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/kindplane

  install:
    desc: Install locally to $GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" ./cmd/kindplane

  test:
    desc: Run tests
    cmds:
      - go test -v -race ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:short:
    desc: Run short tests only
    cmds:
      - go test -v -short ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run linter and fix issues
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - command -v goimports >/dev/null && goimports -w . || echo "goimports not installed, skipping"

  tidy:
    desc: Tidy and verify dependencies
    cmds:
      - go mod tidy
      - go mod verify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  dev:
    desc: Build and show help
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} --help

  dev:init:
    desc: Build and run init command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} init --force

  dev:up:
    desc: Build and run up command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} up

  dev:down:
    desc: Build and run down command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} down

  dev:status:
    desc: Build and run status command
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} status

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  release:snapshot:
    desc: Create a snapshot release (requires goreleaser)
    cmds:
      - goreleaser release --snapshot --clean

  release-tag:
    desc: "Create and push a release tag (usage: task release-tag TAG=v1.0.0)"
    requires:
      vars: [TAG]
    preconditions:
      - sh: echo "{{.TAG}}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'
        msg: "TAG must be a valid semver (e.g., v1.0.0 or v1.0.0-rc.1)"
      - sh: '[ -z "$(git status --porcelain)" ]'
        msg: "Working directory is not clean. Commit or stash changes first."
      - sh: '[ "$(git branch --show-current)" = "main" ]'
        msg: "Must be on main branch to create a release"
      - sh: git fetch origin main --tags
        msg: "Failed to fetch from origin"
      - sh: '[ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ]'
        msg: "Local main is not up to date with origin/main. Run 'git pull' first."
      - sh: 'test -z "$(git tag -l "{{.TAG}}")"'
        msg: "Tag {{.TAG}} already exists"
    cmds:
      - echo "Creating release {{.TAG}} at commit $(git rev-parse --short HEAD)..."
      - git tag -a "{{.TAG}}" -m "Release {{.TAG}}"
      - git push origin "{{.TAG}}"
      - echo "Tag {{.TAG}} pushed. GitHub Actions release workflow triggered."
      - echo "Monitor at https://github.com/kanzifucius/kindplane/actions"

  tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/goreleaser/goreleaser@latest

  # Documentation tasks
  docs:generate:
    desc: Generate CLI reference documentation from Cobra commands
    deps: [build]
    cmds:
      - go run ./cmd/gendocs
      - echo "CLI documentation generated in docs/cli-reference/"

  docs:serve:
    desc: Serve documentation locally with hot reload (Docker)
    cmds:
      - docker run --rm -it -p 8000:8000 -v {{.ROOT_DIR}}:/docs squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000

  docs:build:
    desc: Build documentation site (Docker)
    cmds:
      - docker run --rm -v {{.ROOT_DIR}}:/docs squidfunk/mkdocs-material build --strict

  docs:clean:
    desc: Remove built documentation
    cmds:
      - rm -rf site/

  # Versioned documentation tasks (using mike)
  docs:version:deploy:
    desc: "Deploy a versioned doc (usage: task docs:version:deploy VERSION=1.0.0)"
    requires:
      vars: [VERSION]
    cmds:
      - |
        docker run --rm -v {{.ROOT_DIR}}:/docs -v ~/.gitconfig:/root/.gitconfig:ro \
          -w /docs squidfunk/mkdocs-material \
          sh -c "pip install mike && mike deploy {{.VERSION}}"

  docs:version:list:
    desc: List all deployed documentation versions
    cmds:
      - |
        docker run --rm -v {{.ROOT_DIR}}:/docs -w /docs squidfunk/mkdocs-material \
          sh -c "pip install mike && mike list"

  docs:version:serve:
    desc: Serve versioned documentation locally
    cmds:
      - |
        docker run --rm -it -p 8000:8000 -v {{.ROOT_DIR}}:/docs -w /docs squidfunk/mkdocs-material \
          sh -c "pip install mike && mike serve --dev-addr=0.0.0.0:8000"
