name: Bug Report
description: File a bug report to help us improve kindplane
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        1. Run 'kindplane init'
        2. Configure...
        3. Run 'kindplane up'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Any error messages or relevant logs
      placeholder: Paste error messages or logs here...
      render: shell

  - type: input
    id: version
    attributes:
      label: kindplane Version
      description: The version of kindplane you're using
      placeholder: e.g., v1.0.0 or dev build
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: The version of Go used to build kindplane (if building from source)
      placeholder: e.g., go1.25.0

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Your operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration File
      description: Your kindplane.yaml configuration (please redact any secrets or sensitive information)
      placeholder: |
        cluster:
          name: my-cluster
        ...
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might be helpful
      placeholder: Add any other context about the problem here...
