name: Feature Request
description: Suggest a new feature or enhancement for kindplane
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about your use case and proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the use case?
      placeholder: |
        As a [type of user], I want to [goal] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: If applicable, provide examples of how this feature would be used
      placeholder: |
        ```bash
        # Example command or configuration
        kindplane example --flag value
        ```
      render: shell

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my workflow
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information about the feature request
      placeholder: Add any other context, screenshots, or mockups here...
