package config

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestDefaultConfigWithComments(t *testing.T) {
	output := DefaultConfigWithComments()

	// Check that header is present
	if !strings.Contains(output, "yaml-language-server") {
		t.Error("Missing yaml-language-server header")
	}
	if !strings.Contains(output, "kindplane configuration file") {
		t.Error("Missing kindplane configuration file comment")
	}
	if !strings.Contains(output, "Generated by 'kindplane init'") {
		t.Error("Missing init comment")
	}

	// Check that it's valid YAML
	var cfg Config
	if err := yaml.Unmarshal([]byte(output), &cfg); err != nil {
		t.Errorf("Generated YAML is not valid: %v", err)
	}

	// Check that key comments are present
	if !strings.Contains(output, "Name of the Kind cluster") {
		t.Error("Missing comment for cluster.name")
	}
	if !strings.Contains(output, "Kubernetes version to use") {
		t.Error("Missing comment for cluster.kubernetesVersion")
	}
	if !strings.Contains(output, "Crossplane version to install") {
		t.Error("Missing comment for crossplane.version")
	}

	// Verify it matches DefaultConfig() when parsed
	defaultCfg := DefaultConfig()
	if cfg.Cluster.Name != defaultCfg.Cluster.Name {
		t.Errorf("Cluster name mismatch: got %s, want %s", cfg.Cluster.Name, defaultCfg.Cluster.Name)
	}
	if cfg.Cluster.KubernetesVersion != defaultCfg.Cluster.KubernetesVersion {
		t.Errorf("Kubernetes version mismatch: got %s, want %s", cfg.Cluster.KubernetesVersion, defaultCfg.Cluster.KubernetesVersion)
	}
	if cfg.Crossplane.Version != defaultCfg.Crossplane.Version {
		t.Errorf("Crossplane version mismatch: got %s, want %s", cfg.Crossplane.Version, defaultCfg.Crossplane.Version)
	}
}
