package config

// DefaultConfig returns a configuration with sensible defaults
func DefaultConfig() *Config {
	return &Config{
		Cluster: ClusterConfig{
			Name:              "kindplane-dev",
			KubernetesVersion: "1.29.0",
			Nodes: NodesConfig{
				ControlPlane: 1,
				Workers:      1,
			},
			PortMappings: []PortMapping{
				{
					ContainerPort: 80,
					HostPort:      8080,
					Protocol:      "TCP",
				},
				{
					ContainerPort: 443,
					HostPort:      8443,
					Protocol:      "TCP",
				},
			},
			Ingress: IngressConfig{
				Enabled: true,
			},
		},
		Crossplane: CrossplaneConfig{
			Version: "1.15.0",
			Providers: []ProviderConfig{
				{
					Name:    "provider-kubernetes",
					Package: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.0",
				},
			},
		},
		Credentials: CredentialsConfig{
			AWS: AWSCredentials{
				Source:  "env",
				Profile: "default",
			},
			Azure: AzureCredentials{
				Source: "env",
			},
			Kubernetes: KubernetesCredentials{
				Source: "incluster",
			},
		},
		Charts: []ChartConfig{},
		Compositions: CompositionsConfig{
			Sources: []CompositionSource{},
		},
	}
}

// DefaultConfigWithComments returns the default config as YAML with comments
func DefaultConfigWithComments() string {
	return `# yaml-language-server: $schema=https://raw.githubusercontent.com/kanzifucius/kindplane/main/kindplane.schema.json
# kindplane configuration file
# Generated by 'kindplane init'

cluster:
  # Name of the Kind cluster
  name: kindplane-dev
  
  # Kubernetes version to use (optional, uses Kind default if not specified)
  kubernetesVersion: "1.29.0"
  
  # Full Kind node image path (optional)
  # Use when pulling images through a proxy registry like Artifactory
  # If not specified, defaults to "kindest/node:v<kubernetesVersion>"
  # Examples:
  #   - "artifactory.example.com/kindest/node:v1.29.0"
  #   - "artifactory.example.com/docker.io/kindest/node:v1.29.0"
  # Note: Ensure the proxy registry is configured in trustedCAs if using custom certificates
  # nodeImage: ""
  
  # Node configuration
  nodes:
    controlPlane: 1
    workers: 1
  
  # Port mappings from container to host
  # Format: containerPort:hostPort/protocol
  portMappings:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    - containerPort: 443
      hostPort: 8443
      protocol: TCP
  
  # Mount host paths into Kind nodes
  # extraMounts:
  #   - hostPath: /tmp/kindplane-data
  #     containerPath: /data
  #     readOnly: false
  
  # Ingress controller readiness configuration
  # When enabled, adds required labels and port mappings for ingress controllers
  ingress:
    enabled: true
  
  # Optional: path to a raw Kind config file
  # Settings from kindplane.yaml will be merged on top (kindplane wins)
  # rawConfigPath: ""
  
  # Trusted CA certificates for private registries and workloads
  # trustedCAs:
  #   # CA certificates for private container registries (trusted by containerd)
  #   registries:
  #     - host: "registry.example.com:5000"
  #       caFile: "./certs/registry-ca.crt"
  #     - host: "harbor.internal.com"
  #       caFile: "/path/to/harbor-ca.crt"
  #   # CA certificates mounted for workloads to trust
  #   workloads:
  #     - name: "corporate-root-ca"
  #       caFile: "./certs/corporate-ca.crt"

crossplane:
  # Crossplane version to install
  version: "1.15.0"
  
  # Custom Helm repository URL (optional)
  # Use when pulling charts from a private registry or air-gapped environment
  # If not specified, defaults to https://charts.crossplane.io/stable
  # repo: "https://charts.crossplane.io/stable"
  
  # Inline Helm values for Crossplane installation (optional)
  # These values will be merged with any values files specified below
  # values:
  #   resourcesCrossplane:
  #     limits:
  #       memory: 512Mi
  #   args:
  #     - --enable-composition-functions
  
  # External values files (optional)
  # Values from files are loaded first, then inline values override them
  # valuesFiles:
  #   - ./values/crossplane-values.yaml
  
  # Registry CA bundle for Crossplane (optional)
  # Required when pulling Configuration and Provider packages from private registries with custom certificates
  # Multiple certificates can be specified and will be bundled together into one ConfigMap
  # registryCaBundle:
  #   # Direct paths to CA files (multiple allowed)
  #   caFiles:
  #     - "./certs/corporate-root-ca.crt"
  #     - "./certs/proxy-ca.crt"
  #   # Reference existing workload CAs by name (must be defined in cluster.trustedCAs.workloads)
  #   workloadCARefs:
  #     - "corporate-root-ca"
  
  # Crossplane providers to install
  # Use full OCI package path with version tag
  providers:
    - name: provider-kubernetes
      package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.0
    # Example: Add AWS provider
    # - name: provider-aws
    #   package: xpkg.upbound.io/upbound/provider-aws:v1.1.0
    # Example: Add Azure provider
    # - name: provider-azure
    #   package: xpkg.upbound.io/upbound/provider-azure:v1.0.0

credentials:
  # Kubernetes provider credentials
  kubernetes:
    # Source: incluster (use service account), kubeconfig (use kubeconfig file)
    source: incluster
  
  # AWS credentials configuration (uncomment if using provider-aws)
  # aws:
  #   # Source: env (environment variables), file (credentials file), profile (AWS CLI profile)
  #   source: env
  #   profile: default
  
  # Azure credentials configuration (uncomment if using provider-azure)
  # azure:
  #   # Source: env (environment variables), file (credentials file)
  #   source: env

# Additional Helm charts to install
# Phases: pre-crossplane, post-crossplane, post-providers, final (default), post-eso (deprecated)
charts: []
  # Example: Install External Secrets Operator
  # - name: external-secrets
  #   repo: https://charts.external-secrets.io
  #   chart: external-secrets
  #   version: "0.9.11"
  #   namespace: external-secrets
  #   phase: post-providers
  #   values:
  #     installCRDs: true
  #
  # Example: Install nginx ingress controller
  # - name: nginx-ingress
  #   repo: https://kubernetes.github.io/ingress-nginx
  #   chart: ingress-nginx
  #   version: "4.9.0"
  #   namespace: ingress-nginx
  #   phase: final
  #   wait: true
  #   timeout: 5m
  #   values:
  #     controller:
  #       replicaCount: 1
  #
  # Example: Install cert-manager before Crossplane
  # - name: cert-manager
  #   repo: https://charts.jetstack.io
  #   chart: cert-manager
  #   version: "1.14.0"
  #   namespace: cert-manager
  #   phase: pre-crossplane
  #   values:
  #     installCRDs: true
  #
  # Example: Install with external values file
  # - name: prometheus
  #   repo: https://prometheus-community.github.io/helm-charts
  #   chart: kube-prometheus-stack
  #   namespace: monitoring
  #   valuesFiles:
  #     - ./values/prometheus.yaml

# Crossplane compositions and XRDs
compositions:
  # Sources to load compositions from
  sources: []
  # Example local source:
  # - type: local
  #   path: ./compositions
  #
  # Example git source:
  # - type: git
  #   repo: https://github.com/your-org/crossplane-compositions.git
  #   branch: main
  #   path: /compositions
`
}
