package config

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

const configHeader = `# yaml-language-server: $schema=https://raw.githubusercontent.com/kanzifucius/kindplane/main/kindplane.schema.json
# kindplane configuration file
# Generated by 'kindplane init'

`

func boolPtr(b bool) *bool {
	return &b
}

// DefaultConfig returns a configuration with sensible defaults
func DefaultConfig() *Config {
	return &Config{
		Cluster: ClusterConfig{
			Name:              "kindplane-dev",
			KubernetesVersion: "1.29.0",
			Nodes: NodesConfig{
				ControlPlane: 1,
				Workers:      1,
			},
			PortMappings: []PortMapping{
				{
					ContainerPort: 80,
					HostPort:      8080,
					Protocol:      "TCP",
				},
				{
					ContainerPort: 443,
					HostPort:      8443,
					Protocol:      "TCP",
				},
			},
			Ingress: IngressConfig{
				Enabled: true,
			},
		},
		Crossplane: CrossplaneConfig{
			Version: "2.0.0",
			ImageCache: &ImageCacheConfig{
				Enabled:           boolPtr(true),
				PreloadProviders:  boolPtr(true),
				PreloadCrossplane: boolPtr(true),
				AdditionalImages:  []string{},
			},
			Providers: []ProviderConfig{
				{
					Name:    "provider-kubernetes",
					Package: "xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.0",
				},
			},
		},
		Credentials: CredentialsConfig{
			AWS: AWSCredentials{
				Source:  "env",
				Profile: "default",
			},
			Azure: AzureCredentials{
				Source: "env",
			},
			Kubernetes: KubernetesCredentials{
				Source: "incluster",
			},
		},
		Charts: []ChartConfig{},
		Compositions: CompositionsConfig{
			Sources: []CompositionSource{},
		},
	}
}

// DefaultConfigWithComments returns the default config as YAML with comments
func DefaultConfigWithComments() string {
	cfg := DefaultConfig()

	// Build yaml.Node tree with comments
	rootNode, err := marshalWithComments(cfg)
	if err != nil {
		// Fallback to standard marshalling if comment-aware marshalling fails
		data, marshalErr := yaml.Marshal(cfg)
		if marshalErr != nil {
			return fmt.Sprintf("# Error generating config: %v\n%v", err, marshalErr)
		}
		return configHeader + string(data)
	}

	// Encode the node tree to YAML
	var buf bytes.Buffer
	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)
	if err := encoder.Encode(rootNode); err != nil {
		// Fallback to standard marshalling
		data, marshalErr := yaml.Marshal(cfg)
		if marshalErr != nil {
			return fmt.Sprintf("# Error generating config: %v\n%v", err, marshalErr)
		}
		return configHeader + string(data)
	}
	if err := encoder.Close(); err != nil {
		// Fallback to standard marshalling
		data, marshalErr := yaml.Marshal(cfg)
		if marshalErr != nil {
			return fmt.Sprintf("# Error generating config: %v\n%v", err, marshalErr)
		}
		return configHeader + string(data)
	}

	// Prepend header and return
	return configHeader + buf.String()
}
